language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - pypy
services:
  - memcached
install: python setup.py install
before_script: pip install -r test-requirements.txt
script:
  - flake8
  - nosetests
  - python -c 'import memcache; memcache._doctest()'
